export enum Errors {
  LOAN_NOT_FOUND = 'LOAN_NOT_FOUND',
  INVALID_ID = 'INVALID_ID',
  LOAN_NOT_APPROVED = 'LOAN_NOT_APPROVED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
